apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-server
    spec:
      containers:
      - name: demo-container
        # image: us.gcr.io/real-estate-system-202806/demo:v1
        image: us.gcr.io/real-estate-206706/demo:v3
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: demo-service
  name: demo-service
spec:
  ports:
  - name: demo-service
    port: 80
    targetPort: 80
  selector:
    app: demo-server
  type: LoadBalancer